language: cpp
sudo: false

jobs:
  include:
    - stage: format check
      script: ./tools/check_style.sh
    - stage: build and test
      os: linux
#      compiler: clang
      addons:
        apt:
          sources:
          - llvm-toolchain-precise-3.6
          - ubuntu-toolchain-r-test
          packages:
          - liblapack-dev
          - libfftw3-dev
          - clang-3.6
          - gfortran
      env:
        - NAME='clang'
        - CXX_COMPILER='clang++-3.6'
        - C_COMPILER='clang-3.6'
        - Fortran_COMPILER='gfortran'
        - PYTHON_VER='3.6'
        - BUILD_TYPE='release'
      install:
      - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
      - bash miniconda.sh -b -p $HOME/miniconda
      - export PATH="$HOME/miniconda/bin:$PATH"
      - hash -r
      - conda config --set always_yes yes --set changeps1 no
      - conda update -q conda
      - conda info -a
      - conda create -q -n helpme python=$PYTHON_VER numpy cmake
      - source activate helpme
      - conda list
      before_script:
      - python -V
      - python -c 'import numpy; print(numpy.version.version)'
      - cd ${TRAVIS_BUILD_DIR}
      - export CXX=${CXX_COMPILER}
      - export CC=${C_COMPILER}
      - export FC=${Fortran_COMPILER}
      - export CTEST_OUTPUT_ON_FAILURE=1
      - ${CXX_COMPILER} --version
      - ${Fortran_COMPILER} --version
      - ${C_COMPILER} --version
      - >
          cmake -Bbuild -H.
          -DCMAKE_BUILD_TYPE=${BUILD_TYPE}
          -DCMAKE_CXX_COMPILER=${CXX_COMPILER}
          -DCMAKE_C_COMPILER=${C_COMPILER}
          -DCMAKE_Fortran_COMPILER=${Fortran_COMPILER}
          -DPYTHON_EXECUTABLE="${HOME}/miniconda/envs/helpme/bin/python"
      - cd build
      - make -j 2
      - ls -R
      script: ctest -VV -j 2
    - stage: build and test
      os: linux
#      compiler: clang
      addons:
        apt:
          sources:
          - llvm-toolchain-precise-3.6
          - ubuntu-toolchain-r-test
          packages:
          - liblapack-dev
          - libfftw3-dev
          - g++-4.9
          - gcc-4.9
          - gfortran-4.9
      env:
        - CXX_COMPILER='g++-4.9'
        - PYTHON_VER='2.7'
        - C_COMPILER='gcc-4.9'
        - Fortran_COMPILER='gfortran-4.9'
        - BUILD_TYPE='release'
        - NAME='gcc'
      install:
      - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
      - bash miniconda.sh -b -p $HOME/miniconda
      - export PATH="$HOME/miniconda/bin:$PATH"
      - hash -r
      - conda config --set always_yes yes --set changeps1 no
      - conda update -q conda
      - conda info -a
      - conda create -q -n helpme python=$PYTHON_VER numpy cmake
      - source activate helpme
      - conda list
      before_script:
      - python -V
      - python -c 'import numpy; print(numpy.version.version)'
      - cd ${TRAVIS_BUILD_DIR}
      - export CXX=${CXX_COMPILER}
      - export CC=${C_COMPILER}
      - export FC=${Fortran_COMPILER}
      - export CTEST_OUTPUT_ON_FAILURE=1
      - ${CXX_COMPILER} --version
      - ${Fortran_COMPILER} --version
      - ${C_COMPILER} --version
      - >
          cmake -Bbuild -H.
          -DCMAKE_BUILD_TYPE=${BUILD_TYPE}
          -DCMAKE_CXX_COMPILER=${CXX_COMPILER}
          -DCMAKE_C_COMPILER=${C_COMPILER}
          -DCMAKE_Fortran_COMPILER=${Fortran_COMPILER}
          -DPYTHON_EXECUTABLE="${HOME}/miniconda/envs/helpme/bin/python"
      - cd build
      - make -j 2
      - ls -R
      script: ctest -VV -j 2
